-- MySQL Script generated by MySQL Workbench
-- Sat Jun  4 23:48:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_ID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `auth_cookie` VARCHAR(500) NULL,
  `cookie_selector` VARCHAR(100) NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `user_ID_UNIQUE` (`user_ID` ASC) VISIBLE,
  UNIQUE INDEX `cookie_selector_UNIQUE` (`cookie_selector` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `teacher_ID` INT NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`teacher_ID`),
  INDEX `fk_Teacher_User_idx` (`teacher_ID` ASC) VISIBLE,
  UNIQUE INDEX `User_user_ID_UNIQUE` (`teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_User`
    FOREIGN KEY (`teacher_ID`)
    REFERENCES `mydb`.`User` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Class` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `class_ID` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  `teacher_ID` INT NOT NULL,
  PRIMARY KEY (`class_ID`),
  UNIQUE INDEX `class_ID_UNIQUE` (`class_ID` ASC) VISIBLE,
  INDEX `fk_Class_Teacher1_idx` (`teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Class_Teacher1`
    FOREIGN KEY (`teacher_ID`)
    REFERENCES `mydb`.`Teacher` (`teacher_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_ID` INT NOT NULL,
  `class_ID` INT NOT NULL,
  PRIMARY KEY (`student_ID`),
  INDEX `fk_Student_User1_idx` (`student_ID` ASC) VISIBLE,
  UNIQUE INDEX `User_user_ID_UNIQUE` (`student_ID` ASC) VISIBLE,
  INDEX `fk_Student_Class1_idx` (`class_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_User1`
    FOREIGN KEY (`student_ID`)
    REFERENCES `mydb`.`User` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Class1`
    FOREIGN KEY (`class_ID`)
    REFERENCES `mydb`.`Class` (`class_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `subject_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `shortname` VARCHAR(45) NOT NULL,
  `teacher_ID` INT NULL,
  PRIMARY KEY (`subject_ID`),
  INDEX `fk_Subject_Teacher1_idx` (`teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Teacher1`
    FOREIGN KEY (`teacher_ID`)
    REFERENCES `mydb`.`Teacher` (`teacher_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `group_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `class_ID` INT NOT NULL,
  PRIMARY KEY (`group_ID`),
  UNIQUE INDEX `group_ID_UNIQUE` (`group_ID` ASC) VISIBLE,
  INDEX `fk_Group_Class1_idx` (`class_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Group_Class1`
    FOREIGN KEY (`class_ID`)
    REFERENCES `mydb`.`Class` (`class_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_ID` INT NOT NULL AUTO_INCREMENT,
  `subject_ID` INT NOT NULL,
  `group_ID` INT NOT NULL,
  `teacher_ID` INT NOT NULL,
  PRIMARY KEY (`course_ID`),
  UNIQUE INDEX `course_ID_UNIQUE` (`course_ID` ASC) VISIBLE,
  INDEX `fk_Course_Subject1_idx` (`subject_ID` ASC) VISIBLE,
  INDEX `fk_Course_Group1_idx` (`group_ID` ASC) VISIBLE,
  INDEX `fk_Course_Teacher1_idx` (`teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Subject1`
    FOREIGN KEY (`subject_ID`)
    REFERENCES `mydb`.`Subject` (`subject_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Group1`
    FOREIGN KEY (`group_ID`)
    REFERENCES `mydb`.`Group` (`group_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Teacher1`
    FOREIGN KEY (`teacher_ID`)
    REFERENCES `mydb`.`Teacher` (`teacher_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mark_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mark_category` (
  `category_ID` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `weight` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `teacher_ID` INT NULL,
  PRIMARY KEY (`category_ID`),
  UNIQUE INDEX `category_ID_UNIQUE` (`category_ID` ASC) VISIBLE,
  INDEX `fk_Mark_category_Teacher1_idx` (`teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Mark_category_Teacher1`
    FOREIGN KEY (`teacher_ID`)
    REFERENCES `mydb`.`Teacher` (`teacher_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mark_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mark_type` (
  `mark_type_ID` INT NOT NULL AUTO_INCREMENT,
  `mark` VARCHAR(1) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mark_type_ID`),
  UNIQUE INDEX `mark_type_ID_UNIQUE` (`mark_type_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mark` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mark` (
  `mark_ID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `latka` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `course_ID` INT NOT NULL,
  `student_ID` INT NOT NULL,
  `mark_category_ID` INT NOT NULL,
  `mark_type_ID` INT NOT NULL,
  PRIMARY KEY (`mark_ID`),
  UNIQUE INDEX `mark_ID_UNIQUE` (`mark_ID` ASC) VISIBLE,
  INDEX `fk_Mark_Course1_idx` (`course_ID` ASC) VISIBLE,
  INDEX `fk_Mark_Student1_idx` (`student_ID` ASC) VISIBLE,
  INDEX `fk_Mark_Mark_category1_idx` (`mark_category_ID` ASC) VISIBLE,
  INDEX `fk_Mark_Mark_type1_idx` (`mark_type_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Mark_Course1`
    FOREIGN KEY (`course_ID`)
    REFERENCES `mydb`.`Course` (`course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mark_Student1`
    FOREIGN KEY (`student_ID`)
    REFERENCES `mydb`.`Student` (`student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mark_Mark_category1`
    FOREIGN KEY (`mark_category_ID`)
    REFERENCES `mydb`.`Mark_category` (`category_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mark_Mark_type1`
    FOREIGN KEY (`mark_type_ID`)
    REFERENCES `mydb`.`Mark_type` (`mark_type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_in_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_in_group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student_in_group` (
  `student_ID` INT NOT NULL,
  `group_ID` INT NOT NULL,
  PRIMARY KEY (`student_ID`, `group_ID`),
  INDEX `fk_Student_has_Group_Group1_idx` (`group_ID` ASC) VISIBLE,
  INDEX `fk_Student_has_Group_Student1_idx` (`student_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Group_Student1`
    FOREIGN KEY (`student_ID`)
    REFERENCES `mydb`.`Student` (`student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Group_Group1`
    FOREIGN KEY (`group_ID`)
    REFERENCES `mydb`.`Group` (`group_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Folder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Folder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Folder` (
  `folder_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `private` TINYINT NOT NULL,
  `parent_ID` INT NULL,
  `user_ID` INT NOT NULL,
  UNIQUE INDEX `folder_ID_UNIQUE` (`folder_ID` ASC) VISIBLE,
  PRIMARY KEY (`folder_ID`),
  INDEX `fk_folder_folder1_idx` (`parent_ID` ASC) VISIBLE,
  INDEX `fk_Folder_User1_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `fk_folder_folder1`
    FOREIGN KEY (`parent_ID`)
    REFERENCES `mydb`.`Folder` (`folder_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Folder_User1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `mydb`.`User` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`File` ;

CREATE TABLE IF NOT EXISTS `mydb`.`File` (
  `file_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `file_type` VARCHAR(45) NOT NULL,
  `folder_ID` INT NOT NULL,
  PRIMARY KEY (`file_ID`),
  UNIQUE INDEX `filer_ID_UNIQUE` (`file_ID` ASC) VISIBLE,
  INDEX `fk_File_Folder1_idx` (`folder_ID` ASC) VISIBLE,
  CONSTRAINT `fk_File_Folder1`
    FOREIGN KEY (`folder_ID`)
    REFERENCES `mydb`.`Folder` (`folder_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
